### ISSUE TITLE
Set title in file properties of PDF file

### ISSUE THREAD

**Issue by INOPIAE** [Flayms/Markdown2Pdf#71]
Is there a way to set the title property in the file properties in the generated PDF file.
As far as I can see the filename of the html file is taken as title property.
![image](https://github.com/Flayms/Markdown2Pdf/assets/2772829/29d61fbf-e666-42cb-b0c9-3a3859ea7b2d)

**Comment by INOPIAE** [comment]
Sounds good.
Once working on the file properties may be it is worth to add other file properties as well. e.g. Author, Subject and Keywords
Here an idea [https://stackoverflow.com/questions/51153026/puppeteer-pdf-title-and-author-metadata](https://stackoverflow.com/questions/51153026/puppeteer-pdf-title-and-author-metadata)

Default settings could be:
Title: filename
Author: empty
Subject: empty
Keywords: empty

**Comment by Flayms** [comment]
Alright, gonna set the title over the HTML.
For the other metadata there's no puppeteer support but might be adjustable with https://github.com/UglyToad/PdfPig which I am already using for generating the TOC page numbers.

**Comment by Flayms** [comment]
With PdfPig it's easy to read the Metadata, however It seems like It can't be used it for editing it. Currently still looking for an easy way to edit XMP metadata in C#. Exiftool is nice but would need to create a wrapper for it that also works cross-platform. This sounds quite painful.
