### ISSUE TITLE
How can I add img element in HeaderHtml?

### ISSUE THREAD

**Issue by ABatenev** [Flayms/Markdown2Pdf#72]
If I add img tag in HeaderHtml, for example:
`HeaderHtml = "<img src=\"test.png\" alt =\"Text\"/>"`
Or
`HeaderHtml = "<img src=\"https://mobile.photoprocenter.ru/files/4552_0.jpg\" alt =\"Text\"/>"`
The image is not displayed, no matter what path I specify.

**Comment by Flayms** [comment]
Take a look at https://github.com/puppeteer/puppeteer/issues/2443
It seems like this functionality is not supported within puppeteer.
Try base64 encoding the image.

Let me know if this works!

**Comment by ABatenev** [comment]
Yes? this work for me, thanks!
